apiVersion: batch/v1
kind: Job
metadata:
  name: vault-bootstrap-postgres
  namespace: vault
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: vault-admin
      restartPolicy: OnFailure
      containers:
      - name: vault
        image: hashicorp/vault:1.14.3
        command: ["/bin/sh","-c"]
        args:
          - |
            # Policies schreiben
            for f in /policies/*.hcl; do
              vault policy write $(basename $f .hcl) $f
            done

            # Role aus ConfigMap lesen und schreiben
            ROLE_NAME=$(cat /roles/role-name)
            BOUND_SA=$(cat /roles/bound-service-account-names)
            BOUND_NS=$(cat /roles/bound-service-account-namespaces)
            POLICIES=$(cat /roles/policies)
            TTL=$(cat /roles/ttl)

            vault write auth/kubernetes/role/$ROLE_NAME \
              bound_service_account_names=$BOUND_SA \
              bound_service_account_namespaces=$BOUND_NS \
              policies=$POLICIES \
              ttl=$TTL
        volumeMounts:
        - name: vault-policies
          mountPath: /policies
        - name: vault-roles
          mountPath: /roles
      volumes:
      - name: vault-policies
        configMap:
          name: vault-policies
      - name: vault-roles
        configMap:
          name: vault-role-postgres-infra
