apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: traefik-external
spec:
  chart:
    spec:
      chart: traefik
      version: "v38.0.2"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create   # CRDs automatisch installieren
  values:
    additionalArguments:
      - "--providers.kubernetescrd"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    service:
      type: LoadBalancer
