apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepo-redhat-cop.yaml
  - helmrepo-jetstack.yaml
  - helmrepo-bitnami.yaml
  - helmrepo-traefik.yaml
  - helmrepo-gitlab.yaml
  - helmrepo-sonarqube.yaml
  - helmrepo-hashicorp.yaml
  - helmrepo-minio.yaml
  - helmrepo-grafana.yaml
  #- helmrepo-mastodon.yaml
  - helmrepo-cryptpad.yaml