apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - namespace.yaml
  - helmrelease.yaml
  - minio-kms-token.yaml
  - roles
  - policies
  - jobs

configMapGenerator:
  - name: vault-values
    files:
      - values.yaml
  - name: vault-policies
    files:
      - postgres-admin=postgres-infra-admin.hcl

generatorOptions:
  disableNameSuffixHash: true
