apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-config-operator.yaml 
  # Falls du später weitere Operatoren (z.B. Cert-Manager) hinzufügst, 
  # kommen sie einfach hier in die Liste.