apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: media-service-db
  namespace: postgres-infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: media-service-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: postgres/media-service
        property: username
    - secretKey: password
      remoteRef:
        key: postgres/media-service
        property: password
