apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: postgres-infra-role
  namespace: vault
spec:
  roleName: "postgres-infra"
  # Diese Daten stammen aus deiner ursprünglichen ConfigMap 
  boundServiceAccountNames: 
    - "external-secrets"
  boundServiceAccountNamespaces: 
    - "postgres-infra"
  tokenPolicies: 
    - "postgres-admin"
  tokenMaxTtl: 3600